# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  # name of the job is backend
  backend:
    jobs:
      - python_install
      - django_unittests:
          requires:
            - python_install


################################################################################
commands:
  python_install:
    description: |
      install python dependencies
    steps:
    - run: 
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
  django_unittests:
    steps:
    - run:
        command: |
          . venv/bin/activate
          python3 manage.py test
        working_directory: django_backend

  
################################################################################
executors:
  python_environment:
    description: |
      Python Django runtime environment
    docker:
    - image: circleci/python:<<parameters.python>>-browsers
    parameters:
      python:
        default: "3.9"
        type: string
################################################################################
jobs:
  python_install:
    executor: python_environment
    parameters:
      before_install:
        default:
        - checkout
        type: steps
    steps:
    - steps: <<parameters.before_install>>
    - restore_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
    - python_install
    - persist_to_workspace:
        paths:
        - project
        root: ~/
    - save_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
        - "venv"
  django_unittests:
    executor: python_environment
    steps:
    - attach_workspace:
        at: ~/
    - django_unittests
    - store_test_results:
        path: reports/django_unittests
    - store_artifacts:
        path: test-reports/
        destination: python_app

################################################################################
