# Generated by Django 3.1.5 on 2021-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.IntegerField(),
        ),
    ]
